name = "Weapons Balance - CSLA";
author = "johnb43";
tooltip = "Weapons Balance - CSLA";
tooltipOwned = "Weapons Balance - CSLA";
hideName = 0;
hidePicture = 0;
actionName = "Github";
action = "https://github.com/johnb432/Weapons-Balance-CSLA";
description = "A collection of balancing mods made by johnb43.";
overview = "A collection of balancing mods made by johnb43.";
picture = "\z\wb_csla\addons\main\ui\logo_weapons_balance.paa"; // http://getdrawings.com/get-drawing#gun-drawing-in-pencil-27.jpg, http://getdrawings.com/get-drawing#gun-drawing-in-pencil-17.png
logo = "\z\wb_csla\addons\main\ui\logo_weapons_balance.paa";
logoOver = "\z\wb_csla\addons\main\ui\logo_weapons_balance.paa";
logoSmall = "\z\wb_csla\addons\main\ui\logo_weapons_balance.paa";
overviewPicture = "\z\wb_csla\addons\main\ui\logo_weapons_balance.paa";
